name: 매일 인터파크 티켓 정보 수집

on:
  schedule:
    # 매일 아침 8시(한국 시간 = UTC+9)에 실행 -> UTC 기준 23시(전날)
    - cron: '0 23 * * *'
  workflow_dispatch:  # 수동 실행 옵션 추가

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: 저장소 체크아웃
      uses: actions/checkout@v3
      
    - name: Python 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Chrome 설치
      uses: browser-actions/setup-chrome@v1
      
    - name: Chrome 드라이버 설치
      uses: nanasess/setup-chromedriver@v2
        
    - name: 의존성 설치
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 환경 변수 설정
      run: |
        echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" > .env
        echo "ADMIN_CHAT_ID=${{ secrets.ADMIN_CHAT_ID }}" >> .env
      
    - name: 스크립트 실행
      run: |
        # Chrome 드라이버 시작
        chromedriver --version
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        # 파이썬 스크립트 실행
        python telegram_interpark.py 