name: Daily Ticket Crawler

on:
  schedule:
    - cron: "0 0 * * *" # 매일 UTC 00:00 (한국 시간 09:00)에 실행
  workflow_dispatch: # 수동 실행 가능

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create google credentials
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > google.json

      - name: Run crawler
        run: python sheet.py

      - name: Clean up credentials
        if: always()
        run: rm -f google.json
