name: 인터파크 티켓 정보 크롤링

on:
  schedule:
    # 매일 오전 8:30 (한국시간) = UTC 23:30 (전날)
    - cron: '30 23 * * *'
  workflow_dispatch:  # 수동 실행 옵션

jobs:
  crawl-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: Python 설정
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.13'

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Chrome 설치
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb

      - name: 크롤링 및 알림 실행
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
        run: |
          python telegram.py
